-- ================================================================
-- KỊCH BẢN THIẾT LẬP ORACLE LABEL SECURITY (CHUẨN HOÁ VÀ TỰ DỌN DẸP)
-- Thực hiện cho Schema: QLBENHVIEN, Bảng: THONGBAO
-- Đầu vào yêu cầu: Đăng nhập với quyền SYSDBA vào xepdb1
-- ================================================================

ALTER SESSION SET CONTAINER=xepdb1;

-- 1. Giải quyết triệt để lỗi ORA-12458/PLS-00201: Cấp quyền và mở khóa LBACSYS
ALTER USER LBACSYS ACCOUNT UNLOCK IDENTIFIED BY lbacsys;
GRANT INHERIT PRIVILEGES ON USER SYS TO LBACSYS;
GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO SYS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO SYS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_POLICY_ADMIN TO SYS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO SYS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO SYS WITH GRANT OPTION;

-- 2. Dọn Dẹp Sạch Cấu Hình Cũ (Xoá Triệt Để)
BEGIN
    FOR i IN 1..8 LOOP
        BEGIN EXECUTE IMMEDIATE 'DROP USER u' || i || ' CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;
END;
/

BEGIN
    LBACSYS.SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('THONGBAO_POL', 'QLBENHVIEN', 'THONGBAO', drop_column => TRUE);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    LBACSYS.SA_SYSDBA.DROP_POLICY('THONGBAO_POL', drop_column => TRUE);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE QLBENHVIEN.THONGBAO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Khoảng chờ một nhịp để Oracle xoá sạch các schema objects
EXECUTE DBMS_SESSION.SLEEP(1);

-- 3. Bắt đầu tạo mới (Tạo Policy)
BEGIN
    LBACSYS.SA_SYSDBA.CREATE_POLICY(
        policy_name     => 'THONGBAO_POL',
        column_name     => 'OLS_LABEL',
        default_options => 'READ_CONTROL'
    );
END;
/

-- 4. Tạo Cấu Hình OLS Level (Cấp bậc)
BEGIN
    LBACSYS.SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POL', 300, 'GD', 'Ban Giam Doc');
    LBACSYS.SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POL', 200, 'LD', 'Lanh Dao Khoa');
    LBACSYS.SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POL', 100, 'NV', 'Nhan Vien');
END;
/

-- 5. Tạo Cấu Hình OLS Compartment (Khoa)
BEGIN
    LBACSYS.SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POL', 10, 'TH', 'Khoa Tieu Hoa');
    LBACSYS.SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POL', 20, 'TK', 'Khoa Than Kinh');
    LBACSYS.SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POL', 30, 'TM', 'Khoa Tim Mach');
END;
/

-- 6. Tạo Cấu Hình OLS Group (Cơ sở)
BEGIN
    LBACSYS.SA_COMPONENTS.CREATE_GROUP('THONGBAO_POL', 10, 'HCM', 'Ho Chi Minh');
    LBACSYS.SA_COMPONENTS.CREATE_GROUP('THONGBAO_POL', 20, 'HP', 'Hai Phong');
    LBACSYS.SA_COMPONENTS.CREATE_GROUP('THONGBAO_POL', 30, 'HN', 'Ha Noi');
END;
/

-- 7. Tạo Mới Bảng Thông Báo
CREATE TABLE QLBENHVIEN.THONGBAO (
    NOIDUNG   NVARCHAR2(500),
    NGAYGIO   TIMESTAMP DEFAULT SYSTIMESTAMP,
    DIADIEM   NVARCHAR2(200)
);

-- 8. Apply Policy vào bảng (Lệnh này sẽ tự mọc ra cột OLS_LABEL)
BEGIN
    LBACSYS.SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        policy_name   => 'THONGBAO_POL',
        schema_name   => 'QLBENHVIEN',
        table_name    => 'THONGBAO',
        table_options => 'READ_CONTROL'
    );
END;
/

-- 9. Tạo và Cấp Quyền cho 8 Test Users
BEGIN
    FOR i IN 1..8 LOOP
        EXECUTE IMMEDIATE 'CREATE USER u' || i || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO u' || i;
        EXECUTE IMMEDIATE 'GRANT SELECT ON QLBENHVIEN.THONGBAO TO u' || i;
    END LOOP;
END;
/

-- 10. Phân Quyền Nhãn Thực Thế cho Users (Căn Cứ Ảnh 2)
BEGIN
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u1', 'GD:TH,TK,TM:HCM,HP,HN');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u2', 'LD:TM:HCM');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u3', 'LD:TK:HN');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u4', 'NV:TK:HCM');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u5', 'NV:TM:HCM');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u6', 'LD:TM:HCM');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u7', 'LD:TH,TK,TM:HCM,HP,HN');
    LBACSYS.SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POL', 'u8', 'NV:TH:HN');
END;
/

-- 11. Chèn Dữ Liệu và Gán Nhãn Thực Tế (Căn Cứ Ảnh 2)
BEGIN
    -- QLBENHVIEN cần quyền đi xuyên tất cả các Level/Compartment/Group để insert dữ liệu t1->t7
    LBACSYS.SA_USER_ADMIN.SET_USER_PRIVS('THONGBAO_POL','QLBENHVIEN','FULL');
END;
/

INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't1: Gửi đến toàn bộ nhân viên', SYSTIMESTAMP, N'Hội trường', CHAR_TO_LABEL('THONGBAO_POL','NV'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't2: Gửi đến toàn bộ Ban giám đốc', SYSTIMESTAMP, N'Phòng VIP', CHAR_TO_LABEL('THONGBAO_POL','GD'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't3: Gửi đến các lãnh đạo khoa', SYSTIMESTAMP, N'P. Họp 2', CHAR_TO_LABEL('THONGBAO_POL','LD'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't4: Gửi đến lãnh đạo Khoa tiêu hóa', SYSTIMESTAMP, N'Khoa TH', CHAR_TO_LABEL('THONGBAO_POL','LD:TH'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't5: Gửi đến nhân viên Khoa tiêu hóa ở Hồ Chí Minh', SYSTIMESTAMP, N'CS HCM', CHAR_TO_LABEL('THONGBAO_POL','NV:TH:HCM'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't6: Gửi đến nhân viên Khoa tiêu hóa ở Hà Nội', SYSTIMESTAMP, N'CS HN', CHAR_TO_LABEL('THONGBAO_POL','NV:TH:HN'));
INSERT INTO QLBENHVIEN.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL) VALUES (N't7: Gửi đến lãnh đạo Khoa tiêu hóa và Khoa thần kinh tại Hải Phòng', SYSTIMESTAMP, N'CS HP', CHAR_TO_LABEL('THONGBAO_POL','LD:TH,TK:HP'));

COMMIT;

EXIT;
