--XÓA DANH SÁCH NGƯỜI DÙNG ĐỂ CHẠY LẠI NẾU CÓ
--XÓA NGƯỜI TẠO
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLBENHVIEN CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER QLBENHVIEN IDENTIFIED BY 123;
GRANT CREATE SESSION TO QLBENHVIEN;
GRANT CREATE TABLE TO QLBENHVIEN WITH ADMIN OPTION;
GRANT CREATE VIEW TO QLBENHVIEN WITH ADMIN OPTION;
ALTER USER QLBENHVIEN QUOTA UNLIMITED ON USERS;
GRANT CREATE USER TO QLBENHVIEN WITH ADMIN OPTION;
GRANT CREATE ROLE TO QLBENHVIEN WITH ADMIN OPTION;
GRANT AUDIT SYSTEM TO QLBENHVIEN WITH ADMIN OPTION;
GRANT AUDIT ANY TO QLBENHVIEN WITH ADMIN OPTION;
GRANT AUDIT_VIEWER TO QLBENHVIEN WITH ADMIN OPTION;
GRANT AUDIT_ADMIN TO QLBENHVIEN WITH ADMIN OPTION;
GRANT EXECUTE ON DBMS_RLS TO QLBENHVIEN;
GRANT EXECUTE ON DBMS_RLS_INT TO QLBENHVIEN;
GRANT CREATE ANY CONTEXT TO QLBENHVIEN WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLBENHVIEN WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO QLBENHVIEN WITH ADMIN OPTION;
GRANT ALTER USER TO QLBENHVIEN WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO QLBENHVIEN WITH ADMIN OPTION;
GRANT DROP USER TO QLBENHVIEN WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO QLBENHVIEN WITH ADMIN OPTION;

--ĐĂNG NHẬP VÀO ĐỂ TẠO SCHEMA
CONNECT QLBENHVIEN/123@LOCALHOST:1521/XEPDB1;

-- =========================
-- DROP TABLE
-- =========================
-- BENHNHAN
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE BENHNHAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- NHANVIEN
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- HSBA
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE HSBA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- HSBA_DV
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE HSBA_DV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- DONTHUOC
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE DONTHUOC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =========================
-- TABLE: BENHNHAN
-- =========================
CREATE TABLE BENHNHAN (
    MABN VARCHAR2(10) PRIMARY KEY,
    TENBN VARCHAR2(100),
    PHAI VARCHAR2(10),
    NGAYSINH DATE,
    CCCD VARCHAR2(12),
    SONHA VARCHAR2(50),
    TENDUONG VARCHAR2(100),
    QUANHUYEN VARCHAR2(100),
    TINHTP VARCHAR2(100),
    TIENSUBENH VARCHAR2(255),
    TIENSUBENHGD VARCHAR2(255),
    DIUNGTHUOC VARCHAR2(255)
);

-- =========================
-- TABLE: NHANVIEN
-- =========================
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI VARCHAR2(10),
    NGAYSINH DATE,
    CMND VARCHAR2(12),
    QUEQUAN VARCHAR2(100),
    SODT VARCHAR2(15),
    VAITRO VARCHAR2(30) CHECK (UPPER(VAITRO) IN ('ĐIỀU PHỐI VIÊN', 'BÁC SĨ/Y SĨ', 'KỸ THUẬT VIÊN','BỆNH NHÂN')),
    CHUYENKHOA VARCHAR2(100)
);

-- =========================
-- TABLE: HSBA
-- =========================
CREATE TABLE HSBA (
    MAHSBA VARCHAR2(10) PRIMARY KEY,
    MABN VARCHAR2(10),
    NGAY DATE,
    CHANDOAN VARCHAR2(255),
    DIEUTRI VARCHAR2(255),
    MABS VARCHAR2(10),
    MAKHOA VARCHAR2(5),
    KETLUAN VARCHAR2(255)
);

-- =========================
-- TABLE: HSBA_DV
-- =========================
CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(10),
    LOAIDV VARCHAR2(100),
    NGAYDV DATE,
    MAKTV VARCHAR2(10),
    KETQUA VARCHAR2(255),
    PRIMARY KEY (MAHSBA, LOAIDV, NGAYDV)
);

-- =========================
-- TABLE: DONTHUOC
-- =========================
CREATE TABLE DONTHUOC (
    MAHSBA VARCHAR2(10),
    NGAYDT DATE,
    TENTHUOC VARCHAR2(100),
    LIEUDUNG VARCHAR2(100),
    PRIMARY KEY (MAHSBA, NGAYDT, TENTHUOC)
);

-- =================================
-- ADD FOREIGN KEY HSBA -> BENHNHAN
-- =================================
ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_BN
FOREIGN KEY (MABN)
REFERENCES BENHNHAN(MABN);

-- =================================
-- ADD FOREIGN KEY HSBA -> NHANVIEN
-- =================================
ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_NV
FOREIGN KEY (MABS)
REFERENCES NHANVIEN(MANV);

-- =================================
-- ADD FOREIGN KEY HSBA_DV -> HSBA
-- =================================
ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBADV_HSBA
FOREIGN KEY (MAHSBA)
REFERENCES HSBA(MAHSBA);

-- ====================================
-- ADD FOREIGN KEY HSBA_DV -> NHANVIEN
-- ====================================
ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBADV_NV
FOREIGN KEY (MAKTV)
REFERENCES NHANVIEN(MANV);

-- ====================================
-- ADD FOREIGN KEY DONTHUOC -> HSBA
-- ====================================
ALTER TABLE DONTHUOC
ADD CONSTRAINT FK_DT_HSBA
FOREIGN KEY (MAHSBA)
REFERENCES HSBA(MAHSBA);

-- ====================================
-- INSERT DATA
-- ====================================

-- INSERT 20 DIEU PHOI VIEN
BEGIN
    FOR I IN 1..20 LOOP
        MERGE INTO NHANVIEN T
        USING (
            SELECT 
                'DP' || LPAD(I,3,'0') AS MANV,
                'ĐIỀU PHỐI ' || I AS HOTEN,
                'NAM' AS PHAI,
                DATE '1990-01-01' + I AS NGAYSINH,
                '079' || LPAD(I,8,'0') AS CMND,
                'HCM' AS QUEQUAN,
                '090' || LPAD(I,6,'0') AS SODT,
                'ĐIỀU PHỐI VIÊN' AS VAITRO,
                'TỔNG HỢP' AS CHUYENKHOA
            FROM DUAL
        ) S
        ON (T.MANV = S.MANV)
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MANV, S.HOTEN, S.PHAI, S.NGAYSINH,
            S.CMND, S.QUEQUAN, S.SODT, S.VAITRO, S.CHUYENKHOA
        );
    END LOOP;
END;
/

-- INSERT 100 BAC SI/Y SI
BEGIN
    FOR I IN 1..100 LOOP
        MERGE INTO NHANVIEN T
        USING (
            SELECT 
                'BS' || LPAD(I,3,'0') AS MANV,
                'BÁC SĨ ' || I AS HOTEN,
                'NAM' AS PHAI,
                DATE '1985-01-01' + I AS NGAYSINH,
                '083' || LPAD(I,8,'0') AS CMND,
                'HCM' AS QUEQUAN,
                '091' || LPAD(I,6,'0') AS SODT,
                'BÁC SĨ/Y SĨ' AS VAITRO,
                'NỘI KHOA' AS CHUYENKHOA
            FROM DUAL
        ) S
        ON (T.MANV = S.MANV)
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MANV, S.HOTEN, S.PHAI, S.NGAYSINH,
            S.CMND, S.QUEQUAN, S.SODT, S.VAITRO, S.CHUYENKHOA
        );
    END LOOP;
END;
/

-- INSERT 50 KY THUAT VIEN
BEGIN
    FOR I IN 1..50 LOOP
        MERGE INTO NHANVIEN T
        USING (
            SELECT 
                'KTV' || LPAD(I,3,'0') AS MANV,
                'KỸ THUẬT VIÊN ' || I AS HOTEN,
                'NỮ' AS PHAI,
                DATE '1992-01-01' + I AS NGAYSINH,
                '086' || LPAD(I,8,'0') AS CMND,
                'HCM' AS QUEQUAN,
                '092' || LPAD(I,6,'0') AS SODT,
                'KỸ THUẬT VIÊN' AS VAITRO,
                'XÉT NGHIỆM' AS CHUYENKHOA
            FROM DUAL
        ) S 
        ON (T.MANV = S.MANV)
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MANV, S.HOTEN, S.PHAI, S.NGAYSINH,
            S.CMND, S.QUEQUAN, S.SODT, S.VAITRO, S.CHUYENKHOA
        );
    END LOOP;
END;
/

-- INSERT 100000 BENH NHAN
BEGIN
    FOR I IN 1..500 LOOP
        MERGE INTO BENHNHAN T
        USING (
            SELECT 
                'BN' || LPAD(I,5,'0') AS MABN,
                'BỆNH NHÂN ' || I AS TENBN,
                CASE WHEN MOD(I,2)=0 THEN 'NAM' ELSE 'NỮ' END AS PHAI,
                DATE '2000-01-01' + I AS NGAYSINH,
                '080' || LPAD(I,8,'0') AS CCCD,
                'SỐ ' || I AS SONHA,
                'ĐƯỜNG ABC' AS TENDUONG,
                'QUẬN 1' AS QUANHUYEN,
                'HCM' AS TINHTP,
                NULL AS TIENSUBENH, 
                NULL AS TIENSUBENHGD, 
                NULL AS DIUNGTHUOC
            FROM DUAL
        ) S 
        ON (T.MABN = S.MABN)
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MABN, S.TENBN, S.PHAI, S.NGAYSINH,
            S.CCCD, S.SONHA, S.TENDUONG, S.QUANHUYEN, S.TINHTP,
            S.TIENSUBENH, S.TIENSUBENHGD, S.DIUNGTHUOC
        );
    END LOOP;
END;
/

-- INSERT 500 HSBA
BEGIN
    FOR I IN 1..500 LOOP
        MERGE INTO HSBA T
        USING (
            SELECT 
                'HS' || LPAD(I,3,'0') AS MAHSBA,
                'BN' || LPAD(I,5,'0') AS MABN,
                DATE '2025-01-01' AS NGAY,
                NULL AS CHANDOAN, 
                NULL AS DIEUTRI,
                'BS' || LPAD(MOD(I,100)+1,3,'0') AS MABS,
                'K0001' AS MAKHOA,
                NULL AS KETLUAN
            FROM DUAL
        ) S
        ON (T.MAHSBA = S.MAHSBA)
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MAHSBA, S.MABN, S.NGAY,
            S.CHANDOAN, S.DIEUTRI,
            S.MABS, S.MAKHOA, S.KETLUAN
        );
    END LOOP;
END;
/

-- INSERT 500 HSBA_DV
BEGIN
    FOR I IN 1..500 LOOP
        MERGE INTO HSBA_DV T
        USING (
            SELECT 
                'HS' || LPAD(I,3,'0') AS MAHSBA,
                'XÉT NGHIỆM' AS LOAIDV,
                DATE '2025-01-02' AS NGAYDV,
                'KTV' || LPAD(MOD(I,50)+1,3,'0') AS MAKTV,
                NULL AS KETQUA
            FROM DUAL
        ) S 
        ON (
            T.MAHSBA = S.MAHSBA AND 
            T.LOAIDV = S.LOAIDV AND 
            T.NGAYDV = S.NGAYDV
        )
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MAHSBA, S.LOAIDV, S.NGAYDV, S.MAKTV, S.KETQUA
        );
    END LOOP;
END;
/

-- INSERT 500 DONTHUOC
BEGIN
    FOR I IN 1..500 LOOP
        MERGE INTO DONTHUOC T
        USING (
            SELECT 
                'HS' || LPAD(I,3,'0') AS MAHSBA,
                DATE '2025-01-03' AS NGAYDT,
                'PARACETAMOL' AS TENTHUOC,
                '2 VIÊN/NGÀY' AS LIEUDUNG
            FROM DUAL
        ) S
        ON (
            T.MAHSBA = S.MAHSBA AND 
            T.NGAYDT = S.NGAYDT AND 
            T.TENTHUOC = S.TENTHUOC
        )
        WHEN NOT MATCHED THEN
        INSERT VALUES (
            S.MAHSBA, S.NGAYDT, S.TENTHUOC, S.LIEUDUNG
        );
    END LOOP;
END;
/
COMMIT;

-- CREATE TEST STORED PROCEDURE
CREATE OR REPLACE PROCEDURE SP_UPDATE_CHANDOAN (
    P_MAHSBA VARCHAR2,
    P_CHANDOAN VARCHAR2,
    P_DIEUTRI VARCHAR2,
    P_KETLUAN VARCHAR2
)
AS
BEGIN
    UPDATE HSBA
    SET CHANDOAN = P_CHANDOAN,
        DIEUTRI = P_DIEUTRI,
        KETLUAN = P_KETLUAN
    WHERE MAHSBA = P_MAHSBA;
END;
/

--TẠO DANH SÁCH NGƯỜI DÙNG
--DROP USER BENHNHAN ĐỂ CHẠY LẠI
BEGIN
    FOR R IN (
        SELECT USERNAME 
        FROM all_users 
        WHERE USERNAME LIKE 'BN%'
    ) LOOP
        
        BEGIN
            EXECUTE IMMEDIATE 
            'DROP USER "' || R.USERNAME || '" CASCADE';
        EXCEPTION 
            WHEN OTHERS THEN NULL;
        END;

    END LOOP;
END;
/

--DROP DANH SÁCH NHÂN VIÊN ĐỂ CHẠY LẠI
BEGIN
    FOR R IN (SELECT MANV FROM NHANVIEN) LOOP
        
        BEGIN
            EXECUTE IMMEDIATE 
            'DROP USER "' || R.MANV || '" CASCADE';
        EXCEPTION 
            WHEN OTHERS THEN NULL;
        END;

    END LOOP;
END;
/

--TẠO DANH SÁCH BENHNHAN
BEGIN
    FOR R IN (SELECT MABN FROM BENHNHAN) LOOP
        
        EXECUTE IMMEDIATE 
        'CREATE USER "' || R.MABN || '" IDENTIFIED BY 123';
        
        EXECUTE IMMEDIATE 
        'GRANT CREATE SESSION TO "' || R.MABN || '"';
    
    END LOOP;
END;
/

--TẠO DANH SÁCH NHÂN VIÊN
BEGIN
    FOR R IN (SELECT MANV FROM NHANVIEN) LOOP
        
        EXECUTE IMMEDIATE 
        'CREATE USER "' || R.MANV || '" IDENTIFIED BY 123';
        
        EXECUTE IMMEDIATE 
        'GRANT CREATE SESSION TO "' || R.MANV || '"';
    
    END LOOP;
END;
/


--DROP CÁC ROLE ĐỂ CHẠY LẠI
BEGIN EXECUTE IMMEDIATE 'DROP ROLE BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP ROLE DIEUPHOIVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP ROLE BACSI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP ROLE KYTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--TẠO CÁC ROLE 
CREATE ROLE BENHNHAN;
CREATE ROLE DIEUPHOIVIEN;
CREATE ROLE BACSI;
CREATE ROLE KYTHUATVIEN;


--GÁN ROLE CHO BENHNHANH
BEGIN
    FOR R IN (SELECT MABN FROM BENHNHAN) LOOP
        EXECUTE IMMEDIATE 
        'GRANT BENHNHAN TO "' || R.MABN || '"';
    END LOOP;
END;
/

--GÁN ROLE CHO DIEUPHOIVIEN
BEGIN
    FOR R IN (
        SELECT MANV 
        FROM NHANVIEN 
        WHERE MANV LIKE 'DP%'
    ) LOOP
        EXECUTE IMMEDIATE 
        'GRANT DIEUPHOIVIEN TO "' || R.MANV || '"';
    END LOOP;
END;
/

--GÁN ROLE CHO BACSI
BEGIN
    FOR R IN (
        SELECT MANV 
        FROM NHANVIEN 
        WHERE MANV LIKE 'BS%'
    ) LOOP
        EXECUTE IMMEDIATE 
        'GRANT BACSI TO "' || R.MANV || '"';
    END LOOP;
END;
/

--GÁN ROLE CHO KYTHUATVIEN
BEGIN
    FOR R IN (
        SELECT MANV 
        FROM NHANVIEN 
        WHERE MANV LIKE 'KTV%'
    ) LOOP
        EXECUTE IMMEDIATE 
        'GRANT KYTHUATVIEN TO "' || R.MANV || '"';
    END LOOP;
END;
/

--DÙNG RBAC ĐỂ THIẾT LẬP CHO 'KỸ THUẬT VIÊN' VÀ 'BỆNH NHÂN'
--THIẾT LẬP CHO 'KỸ THUẬT VIÊN'
--TẠO VIEW ĐỂ CÓ THỂ THẤY/ UPDATE ĐƯỢC DÒNG CỦA NGƯỜI ĐÓ
CREATE OR REPLACE VIEW KTV_XEMHSBA_DV AS
SELECT *
FROM HSBA_DV
WHERE MAKTV = USER
WITH CHECK OPTION;

--GÁN VIEW CHO ROLE
GRANT SELECT ON KTV_XEMHSBA_DV TO KYTHUATVIEN;
GRANT UPDATE (KETQUA) ON KTV_XEMHSBA_DV TO KYTHUATVIEN;

--TẠO VIEW ĐỂ THẤY/UPDATE ĐƯỢC THÔNG TIN CÁ NHÂN CHÍNH MÌNH
CREATE OR REPLACE VIEW KTV_XEMTTCANHAN AS
SELECT *
FROM NHANVIEN
WHERE MANV = USER
WITH CHECK OPTION;

--GÁN VIEW CHO ROLE
GRANT SELECT ON KTV_XEMTTCANHAN TO KYTHUATVIEN;
GRANT UPDATE (QUEQUAN, SODT) ON KTV_XEMTTCANHAN TO KYTHUATVIEN;

--THIẾT LẬP CHO 'BỆNH NHÂN'
--TẠO VIEW CHỈ ĐỂ XEM THÔNG TIN VÀ UPDATE CHO CHÍNH MÌNH
CREATE OR REPLACE VIEW BN_XEMTHONGTIN_BN AS
SELECT *
FROM BENHNHAN
WHERE MABN = USER;

--GÁN VIEW CÙNG VỚI UPDATE TRÊN CÁC CỘT THEO ĐỀ
GRANT SELECT, UPDATE (SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON BN_XEMTHONGTIN_BN TO BENHNHAN;

--ÉP THỎA CHÍNH SÁCH BẢO MẬT CHO 'ĐIỀU PHỐI VIÊN' VÀ 'Y SĨ/ BÁC SĨ' THÔNG QUA VPD
--CHO 'ĐIỀU PHỐI VIÊN'
GRANT SELECT, INSERT, UPDATE ON BENHNHAN TO DIEUPHOIVIEN;
GRANT INSERT ON HSBA TO DIEUPHOIVIEN;
GRANT UPDATE (MAKHOA, MABS) ON HSBA TO DIEUPHOIVIEN;
GRANT UPDATE (MAKTV) ON HSBA_DV TO DIEUPHOIVIEN;

--(BỔ SUNG) QUYỀN XEM ĐỂ ĐIỀU PHỐI
GRANT SELECT ON HSBA TO DIEUPHOIVIEN;
GRANT SELECT ON HSBA_DV TO DIEUPHOIVIEN;

--TẠO FUNCTION ĐỂ NGƯỜI ĐÓ THẤY MỖI CHÍNH MÌNH
CREATE OR REPLACE FUNCTION NV_VPD (
    P_SCHEMA IN VARCHAR2,
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MANV = ''' || USER || '''';
END;
/

--DÙNG VPD ĐỂ CHUYỂN CHO CÁC NHÂN VIÊN
--PHÂN QUYỀN CHỈNH SỬA THÊM TRÊN CỘT CHO QUEQUAN VÀ SODT CÙNG QUYỀN SELECT BẢNG
GRANT UPDATE (QUEQUAN, SODT) ON NHANVIEN TO DIEUPHOIVIEN;
GRANT SELECT ON NHANVIEN TO DIEUPHOIVIEN;

--------------------------------------------------
-- CHO 'BÁC SĨ/ Y SĨ'
--------------------------------------------------

--CHO BÁC SĨ THẤY DÒNG CỦA CHÍNH MÌNH
GRANT SELECT ON NHANVIEN TO BACSI;
GRANT UPDATE (QUEQUAN, SODT) ON NHANVIEN TO BACSI;

--XEM CÁC HỒ SƠ BỆNH ÁN MÀ MÌNH ĐÃ ĐIỀU TRỊ
GRANT SELECT ON HSBA TO BACSI;
GRANT UPDATE (CHANDOAN, DIEUTRI, KETLUAN) ON HSBA TO BACSI;

GRANT SELECT ON BENHNHAN TO BACSI;
GRANT UPDATE (TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON BENHNHAN TO BACSI;

GRANT SELECT, INSERT, DELETE ON DONTHUOC TO BACSI;
GRANT UPDATE (TENTHUOC, LIEUDUNG) ON DONTHUOC TO BACSI;

--GRANT QUYỀN CHO 'BÁC SĨ'
GRANT INSERT, DELETE ON HSBA_DV TO BACSI;

--------------------------------------------------
-- FUNCTION CHUNG CHO NHANVIEN
--------------------------------------------------

CREATE OR REPLACE FUNCTION NV_VPD (
    P_SCHEMA VARCHAR2,
    P_OBJECT VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MANV = ''' || USER || '''';
END;
/

--------------------------------------------------
-- FUNCTION CHO BACSI
--------------------------------------------------

CREATE OR REPLACE FUNCTION BS_VPD (
    P_SCHEMA VARCHAR2,
    P_OBJECT VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = ''' || USER || '''';
END;
/

--------------------------------------------------
-- FUNCTION TRÊN BẢNG HSBA
--------------------------------------------------

CREATE OR REPLACE FUNCTION BS_HSBA (
    P_SCHEMA VARCHAR2,
    P_OBJECT VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAHSBA IN (
        SELECT MAHSBA
        FROM HSBA
        WHERE MABS = ''' || USER || '''
    )';
END;
/

--------------------------------------------------
-- FUNCTION TRÊN BẢNG BENHNHAN
--------------------------------------------------

CREATE OR REPLACE FUNCTION BS_HSBENHNHAN (
    P_SCHEMA VARCHAR2,
    P_OBJECT VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABN IN (
        SELECT MABN
        FROM HSBA
        WHERE MABS = ''' || USER || '''
    )';
END;
/

--------------------------------------------------
-- XÓA CÁC POLICY ĐỂ CHẠY LẠI
--------------------------------------------------

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','NHANVIEN','NV_THAY_TTIN_CA_NHAN_SELECT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','NHANVIEN','NV_THAY_TTIN_CA_NHAN_UPDATE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA','BS_THAY_DONG_CHINH_MINH_SELECT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA','BS_THAY_DONG_CHINH_MINH_INSERT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA','BS_THAY_DONG_CHINH_MINH_UPDATE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA','BS_THAY_DONG_CHINH_MINH_DELETE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA_DV','BS_THEM_XOA_DV_SELECT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA_DV','BS_THEM_XOA_DV_INSERT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','HSBA_DV','BS_THEM_XOA_DV_DELETE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','DONTHUOC','BS_THEM_XOA_CAPNHAT_THUOC_SELECT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','DONTHUOC','BS_THEM_XOA_CAPNHAT_THUOC_INSERT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','DONTHUOC','BS_THEM_XOA_CAPNHAT_THUOC_UPDATE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','DONTHUOC','BS_THEM_XOA_CAPNHAT_THUOC_DELETE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','BENHNHAN','BS_CAPNHAT_BENHNHAN_SELECT');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('QLBENHVIEN','BENHNHAN','BS_CAPNHAT_BENHNHAN_UPDATE');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------
-- ADD POLICY NHANVIEN
--------------------------------------------------

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'NHANVIEN',
POLICY_NAME=>'NV_THAY_TTIN_CA_NHAN_SELECT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'NV_VPD',
STATEMENT_TYPES=>'SELECT',
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'NHANVIEN',
POLICY_NAME=>'NV_THAY_TTIN_CA_NHAN_UPDATE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'NV_VPD',
STATEMENT_TYPES=>'UPDATE',
UPDATE_CHECK=>TRUE,
ENABLE=>TRUE);
END;
/

--------------------------------------------------
-- ADD POLICY HSBA
--------------------------------------------------

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA',
POLICY_NAME=>'BS_THAY_DONG_CHINH_MINH_SELECT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_VPD',
STATEMENT_TYPES=>'SELECT',
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA',
POLICY_NAME=>'BS_THAY_DONG_CHINH_MINH_INSERT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_VPD',
STATEMENT_TYPES=>'INSERT',
UPDATE_CHECK => TRUE,
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA',
POLICY_NAME=>'BS_THAY_DONG_CHINH_MINH_UPDATE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_VPD',
STATEMENT_TYPES=>'UPDATE',
UPDATE_CHECK=>TRUE,
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA',
POLICY_NAME=>'BS_THAY_DONG_CHINH_MINH_DELETE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_VPD',
STATEMENT_TYPES=>'DELETE',
ENABLE=>TRUE);
END;
/

--------------------------------------------------
-- ADD POLICY HSBA_DV
--------------------------------------------------

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA_DV',
POLICY_NAME=>'BS_THEM_XOA_DV_SELECT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'SELECT',
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA_DV',
POLICY_NAME=>'BS_THEM_XOA_DV_INSERT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'INSERT',
UPDATE_CHECK => TRUE,
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'HSBA_DV',
POLICY_NAME=>'BS_THEM_XOA_DV_DELETE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'DELETE',
ENABLE=>TRUE);
END;
/

--------------------------------------------------
-- ADD POLICY DONTHUOC
--------------------------------------------------

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'DONTHUOC',
POLICY_NAME=>'BS_THEM_XOA_CAPNHAT_THUOC_SELECT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'SELECT',
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'DONTHUOC',
POLICY_NAME=>'BS_THEM_XOA_CAPNHAT_THUOC_INSERT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'INSERT',
UPDATE_CHECK => TRUE,
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'DONTHUOC',
POLICY_NAME=>'BS_THEM_XOA_CAPNHAT_THUOC_UPDATE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'UPDATE',
UPDATE_CHECK=>TRUE,
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'DONTHUOC',
POLICY_NAME=>'BS_THEM_XOA_CAPNHAT_THUOC_DELETE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBA',
STATEMENT_TYPES=>'DELETE',
ENABLE=>TRUE);
END;
/

--------------------------------------------------
-- ADD POLICY BENHNHAN
--------------------------------------------------

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'BENHNHAN',
POLICY_NAME=>'BS_CAPNHAT_BENHNHAN_SELECT',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBENHNHAN',
STATEMENT_TYPES=>'SELECT',
ENABLE=>TRUE);
END;
/

BEGIN
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA=>'QLBENHVIEN',
OBJECT_NAME=>'BENHNHAN',
POLICY_NAME=>'BS_CAPNHAT_BENHNHAN_UPDATE',
FUNCTION_SCHEMA=>'QLBENHVIEN',
POLICY_FUNCTION=>'BS_HSBENHNHAN',
STATEMENT_TYPES=>'UPDATE',
UPDATE_CHECK=>TRUE,
ENABLE=>TRUE);
END;
/

--DROP CÁC AUDIT
BEGIN
    DBMS_FGA.DROP_POLICY(
        OBJECT_SCHEMA => 'QLBENHVIEN',
        OBJECT_NAME   => 'HSBA',
        POLICY_NAME   => 'AUDIT_HSBA_COLUMN'
    );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_FGA.DROP_POLICY(
        OBJECT_SCHEMA => 'QLBENHVIEN',
        OBJECT_NAME   => 'HSBA_DV',
        POLICY_NAME   => 'AUDIT_HSBA_DV_COLUMN'
    );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_FGA.DROP_POLICY(
        OBJECT_SCHEMA => 'QLBENHVIEN',
        OBJECT_NAME   => 'DONTHUOC',
        POLICY_NAME   => 'AUDIT_DONTHUOC_COLUMN'
    );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--TẠO AUDIT
BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA   => 'QLBENHVIEN',
        OBJECT_NAME     => 'HSBA',
        POLICY_NAME     => 'AUDIT_HSBA_COLUMN',
        STATEMENT_TYPES => 'UPDATE',
        AUDIT_COLUMN    => 'CHANDOAN, DIEUTRI, KETLUAN',
        ENABLE          => TRUE
    );
END;
/

BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA   => 'QLBENHVIEN',
        OBJECT_NAME     => 'HSBA_DV',
        POLICY_NAME     => 'AUDIT_HSBA_DV_COLUMN',
        STATEMENT_TYPES => 'UPDATE',
        AUDIT_COLUMN    => 'KETQUA',
        ENABLE          => TRUE
    );
END;
/

BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA   => 'QLBENHVIEN',
        OBJECT_NAME     => 'DONTHUOC',
        POLICY_NAME     => 'AUDIT_DONTHUOC_COLUMN',
        STATEMENT_TYPES => 'UPDATE',
        AUDIT_COLUMN    => 'TENTHUOC, LIEUDUNG',
        ENABLE          => TRUE
    );
END;
/